"use strict";$.fn.escape=function(a){return this.each(function(){jQuery(document).on("keydown",this,function(c){var b=((typeof c.keyCode!="undefined"&&c.keyCode)?c.keyCode:c.which);
if(b===27){a.call(this,c);}});});};var navigationRight=jQuery(".menu-wrap");function Navigation(){var c=document.body,f=document.querySelector("#close-button"),b=document.getElementById("open-button"),a=document.getElementById("close-button"),e=false;
function h(){d();}function d(){b.addEventListener("click",g);if(a){a.addEventListener("click",g);}f.addEventListener("click",function(i){var j=i.target;
if(e&&j!==b){g();}});}function g(){if(e){classie.remove(c,"show-menu");}else{classie.add(c,"show-menu");}e=!e;}navigationRight.escape(function(){if(e){classie.remove(c,"show-menu");
classie.remove(b,"active");}e=!e;});h();}function Tabs(){[].slice.call(document.querySelectorAll(".ef-tabs")).forEach(function(a){new CBPFWTabs(a);});}function getDribbbleThumbs(){jQuery.jribbble.setToken(dribbbleToken);
jQuery.jribbble.users(dribbbleName).shots({per_page:numberOfItems}).then(function(b){var a=[];b.forEach(function(c){a.push('<div class="col-md-4 col-sm-4 col-xs-12 mix">');
a.push('<div class="img dribbble-shot">');a.push('<img src="'+c.images.normal+'">');a.push('<div class="overlay-thumb">');a.push('<div class="details">');
a.push('<span class="title">'+c.title+"</span>");a.push("</div>");a.push('<span class="btnBefore"></span><span class="btnAfter"></span>');a.push('<a class="main-portfolio-link" href="'+c.html_url+'" target="_blank">');
a.push("</div>");a.push("</div>");a.push("</div>");});jQuery("#work-grid").html(a.join(""));});}function getSocialButtons(){var a=jQuery(".social-buttons");
if(a.length>0){jQuery("[data-social]").socialButtons();}}$.fn.scrollToTop=function(){jQuery(this).hide().removeAttr("href");if(jQuery(window).scrollTop()!="0"){jQuery(this).fadeIn("slow");
}var a=jQuery(this);jQuery(window).scroll(function(){if(jQuery(window).scrollTop()=="0"){jQuery(a).fadeOut("slow");}else{jQuery(a).fadeIn("slow");}});jQuery(this).on("click",function(){jQuery("html, body").animate({scrollTop:0},"slow");
});};var isMobile={Android:function(){return navigator.userAgent.match(/Android/i);},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i);
},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i);},Opera:function(){return navigator.userAgent.match(/Opera Mini/i);},Windows:function(){return navigator.userAgent.match(/IEMobile/i);
},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows());}};function parallaxScroll(){var b=jQuery(window).scrollTop();
var a=jQuery(".ef-parallax-bg");a.css("background-position","center -"+((b*0.4))+"px");}function historySlider(){var a=jQuery("#history-images");if(a.length>0){a.owlCarousel({singleItem:true,pagination:false,autoPlay:2000,slideSpeed:300});
}}function likeEf(){jQuery(".like-product").on("click",function(){jQuery(this).find("i").toggleClass("press");jQuery(this).find("i").removeClass("ion-ios-heart-outline");
jQuery(this).find("span.like-product").toggleClass("press");if(jQuery(this).find("i").hasClass("press")||jQuery(this).find("i").hasClass("ion-ios-heart-outline")){jQuery(this).find(".output").html(function(a,b){return b*1+1;
});jQuery(this).find("i").addClass("ion-ios-heart");jQuery(this).find("i").removeClass("ion-ios-heart-outline");}else{jQuery(this).find(".output").html(function(a,b){return b*1-1;
});jQuery(this).find("i").removeClass("ion-ios-heart");jQuery(this).find("i").addClass("ion-ios-heart-outline");}});}jQuery(document).ready(function(d){jQuery(".menu-item-has-children, .page_item_has_children").hover(function(){jQuery(this).children(".sub-menu").stop().slideDown(200);
},function(){jQuery(this).children(".sub-menu").stop().slideUp(200);});jQuery("#open-mobile-menu").on("click",function(){var l=jQuery(this);var m=jQuery(".menu-wrap-2");
if(m.hasClass("is-open")){l.removeClass("active");m.removeClass("is-open");}else{m.addClass("is-open");l.addClass("active");}});if(jQuery(".dribble-grid").length>0){getDribbbleThumbs();
}if(navigationRight.length>0){Navigation();}if(!isMobile.any()){jQuery(window).on("scroll",function(){parallaxScroll();});}var k=jQuery(".works-filter");
jQuery("button.nav").on("click",function(){var l=jQuery(this);l.toggleClass("open");k.toggleClass("open");});var a=jQuery("#arch-slider");var c=jQuery(".prev-slide");
var f=jQuery(".next-slide");if(a.length>0){a.owlCarousel({singleItem:true,pagination:false,autoPlay:5000,slideSpeed:300,});c.on("click",function(){a.trigger("owl.prev");
});f.on("click",function(){a.trigger("owl.next");});}var g=jQuery(".single-slider");if(g.length>0){g.owlCarousel({singleItem:true,pagination:false,autoPlay:5000,slideSpeed:300,});
c.on("click",function(){g.trigger("owl.prev");});f.on("click",function(){g.trigger("owl.next");});}var e=jQuery(".team");if(e.length>0){e.owlCarousel({pagination:true,items:3,margin:20,autoHeight:true,itemsDesktop:[1199,3],itemsDesktopSmall:[980,2],itemsTablet:[768,2],itemsMobile:[479,1]});
}var h=jQuery("#tabs-slider");if(h.length>0){h.owlCarousel({singleItem:true,pagination:false,autoPlay:3000,slideSpeed:600,});}var b=jQuery(".js-ui-search");
var j=jQuery(".js-ui-close");var i=jQuery(".js-ui-text");j.on("click",function(){b.toggleClass("open");});i.on("transitionend webkitTransitionEnd oTransitionEnd",function(){if(b.hasClass("open")){i.focus();
}else{return;}});Pace.on("done",function(){jQuery(".cover").addClass("animated fadeOutRight").fadeOut(1000);});jQuery(".popup-video").magnificPopup({type:"iframe",closeOnContentClick:true,closeBtnInside:false,fixedContentPos:true,mainClass:"mfp-no-margins mfp-with-zoom",image:{verticalFit:true},zoom:{enabled:true,duration:300}});
jQuery("#slider-ef").kenburnsy();jQuery("#scroll-top").scrollToTop();likeEf();historySlider();getSocialButtons();Tabs();new WOW().init();});jQuery(window).load(function(b){var a=jQuery("#work-grid");
if(a.length>0){a.isotope({layoutMode:"masonry",transitionDuration:"0.7s",columnWidth:60});}jQuery("a.filter").on("click",function(){var c=jQuery(this).attr("data-filter");
if(c=="all"){a.isotope({filter:".mix"});}else{a.isotope({filter:"."+c});}});jQuery(".filter").on("click",function(){jQuery("a.filter").removeClass("active");
jQuery(this).addClass("active");});});